### ISSUE TITLE
Rework hybrid model layer definition

### ISSUE THREAD

**Issue by nelson-lojo** [in-context-learning-2024/in-context#79]
The current scheme for adding layers is very repetitive. It would be nice if it could be done entirely from yaml. 

Proposal: use some python meta programming magic to auto-import layers from yaml

example:
```yaml
layers:
  - module: "transformers.Mamba"
    name: "MambaMixer"
    config:
      module: "transformers.Mamba"
      name: "MambaConfig"
    positional_args:
      - "arg1"
      - "arg2
    keyword_args:
      some_value: 4 
```
